### ISSUE TITLE
TypeError: ExternalRayDistributedExecutor.collective_rpc() got an unexpected keyword argument 'non_block'

### ISSUE THREAD

**Issue by p81sunshine** [rllm-org/rllm#240]
When I reimplement the DeepSWE using rllm, during rollout, this error cause the enginee crashed.

**Comment by NIL-zhuang** [comment]
same issue here, reproduce with train_math_with_tools + Qwen3

**Comment by NIL-zhuang** [comment]
Error log below, I printed the prompt, sampling params and request_id, without finding any `non_block`
The error happens in verl.verl.workers.rollout.vllm_rollout.vllm_async_server.py:320

<img width="690" height="293" alt="Image" src="https://github.com/user-attachments/assets/f7e3d596-d473-4339-9ced-492047398331" />

```log
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [dump_input.py:79] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.0011791790667640134, prefix_cache_stats=PrefixCacheStats(reset=True, requests=1, queries=325, hits=0), spec_decoding_stats=None, kv_connector_stats=None, num_corrupted_reqs=0)
(AsyncvLLMServer pid=115796) {'prompt_token_ids': [151644, 8948, 198, 2610, 525, 264, 6888, 17847, 429, 646, 3270, 10135, 311, 11625, 6888, 5322, 382, 2, 13852, 271, 2610, 1231, 1618, 825, 476, 803, 5746, 311, 7789, 448, 279, 1196, 3239, 382, 2610, 525, 3897, 448, 729, 32628, 2878, 366, 15918, 1472, 15918, 29, 11874, 9492, 510, 27, 15918, 397, 9640, 220, 341, 262, 330, 1313, 788, 330, 1688, 756, 262, 330, 1688, 788, 341, 414, 330, 606, 788, 330, 12669, 756, 414, 330, 4684, 788, 330, 17174, 13027, 2038, 304, 264, 42754, 291, 4573, 13, 5184, 3059, 323, 5297, 2550, 41737, 10346, 414, 330, 13786, 788, 341, 286, 330, 1313, 788, 330, 1700, 756, 286, 330, 13193, 788, 341, 688, 330, 1851, 788, 341, 310, 330, 1313, 788, 330, 917, 756, 310, 330, 4684, 788, 330, 17174, 13027, 2038, 304, 264, 42754, 291, 4573, 13, 5184, 3059, 323, 5297, 2550, 41737, 10040, 688, 1153, 688, 330, 14150, 788, 341, 310, 330, 1313, 788, 330, 11662, 756, 310, 330, 4684, 788, 330, 27309, 11320, 882, 304, 6486, 1573, 18405, 700, 756, 310, 330, 2258, 788, 220, 16, 17, 198, 688, 456, 286, 1153, 286, 330, 6279, 788, 2278, 688, 330, 1851, 698, 286, 5133, 414, 456, 262, 456, 220, 456, 921, 522, 15918, 1339, 2461, 1817, 729, 1618, 11, 470, 264, 2951, 1633, 448, 729, 829, 323, 5977, 2878, 220, 151657, 151658, 11874, 9492, 510, 151657, 198, 4913, 606, 788, 366, 1688, 11494, 8066, 330, 16370, 788, 366, 2116, 56080, 40432, 31296, 151658, 151645, 198, 151644, 872, 198, 3862, 3000, 1931, 5109, 400, 87, 3, 323, 400, 88, 54876, 2176, 7046, 1091, 220, 16, 11, 1741, 429, 57960, 839, 3212, 59, 2359, 7021, 61, 87, 59, 1291, 11730, 59, 839, 4178, 59, 2359, 2075, 47822, 19, 88, 11035, 1291, 11730, 16, 15, 12947, 7379, 400, 4130, 12947, 151645, 198, 151644, 77091, 198]}
(AsyncvLLMServer pid=115796) SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.6, top_p=0.95, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=71888, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, structured_outputs=None, extra_args=None)
(AsyncvLLMServer pid=115796) 093e6ad5-52d2-4558-8370-c0361cd135b9
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710] EngineCore encountered a fatal error.
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710] Traceback (most recent call last):
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 701, in run_engine_core
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     engine_core.run_busy_loop()
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 728, in run_busy_loop
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     self._process_engine_step()
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 754, in _process_engine_step
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     outputs, model_executed = self.step_fn()
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]                               ^^^^^^^^^^^^^^
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 284, in step
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     model_output = self.execute_model_with_error_logging(
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 270, in execute_model_with_error_logging
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     raise err
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 261, in execute_model_with_error_logging
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     return model_fn(scheduler_output)
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 103, in execute_model
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]     output = self.collective_rpc("execute_model",
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(AsyncvLLMServer pid=115796) (EngineCore_DP0 pid=117090) ERROR 10-11 20:36:47 [core.py:710] TypeError: ExternalZeroMQDistributedExecutor.collective_rpc() got an unexpected keyword argument 'non_block'
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480] AsyncLLM output_handler failed.
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480] Traceback (most recent call last):
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 439, in output_handler
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480]     outputs = await engine_core.get_output_async()
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480]   File "/usr/local/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 846, in get_output_async
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480]     raise self._format_exception(outputs) from None
(AsyncvLLMServer pid=115796) ERROR 10-11 20:36:47 [async_llm.py:480] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
```

**Comment by NIL-zhuang** [comment]
Introduced in https://github.com/volcengine/verl/pull/2246
Try modify `verl.verl.workers.rollout.vllm_rollout.vllm_async_server.py:156`, add non_block in the function
@p81sunshine 
<img width="587" height="391" alt="Image" src="https://github.com/user-attachments/assets/cc3a8015-c9b4-4298-9bec-608f6d5b4fa4" />

**Comment by p81sunshine** [comment]
> Introduced in [volcengine/verl#2246](https://github.com/volcengine/verl/pull/2246) Try modify `verl.verl.workers.rollout.vllm_rollout.vllm_async_server.py:156`, add non_block in the function [@p81sunshine](https://github.com/p81sunshine) <img alt="Image" width="587" height="391" src="https://private-user-images.githubusercontent.com/46214362/500147553-cc3a8015-c9b4-4298-9bec-608f6d5b4fa4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxOTMyNDIsIm5iZiI6MTc2MDE5Mjk0MiwicGF0aCI6Ii80NjIxNDM2Mi81MDAxNDc1NTMtY2MzYTgwMTUtYzliNC00Mjk4LTliZWMtNjA4ZjZkNWI0ZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDExVDE0MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYmNlZTc3Yzc2ZDVmZjEwYTRlMDhkMTZjMmM2YTcwODZmYjA4OWJjN2JlZWIyZTM1NTFlYmFkMGMwYzg0MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._iZ8eLxrAWfWaY_xKlSnRHmI8paTbsQoCac_JImlIus">


Thanks! :) 

Actually, I added this yesterday with the assistance of Claude 3.5. I find that this parameter doesn't seem to be used by this function. I also wonder why other people don't encounter this problem.
